version: '{branch}{build}'
pull_requests:
  do_not_increment_build_number: true
configuration: Release
before_build:
- cmd: nuget restore xFunc.sln
build:
  project: xFunc.sln
  verbosity: minimal
deploy: off
