version: '{branch}{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: YI6EFXDLg4sSRbxxqZdTI21IAWMt55JfDTTDpA6ljw7zq5UmXi9x5vbagzua5hqe
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore xFunc.sln
build:
  project: xFunc.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -output:coverage.xml -target:"packages\xunit.runner.console.2.4.1\tools\net472\xunit.console.x86.exe" -targetargs:"xFunc.Tests\bin\Release\xFunc.Tests.dll -nologo -noshadow" -excludebyattribute:*.ExcludeFromCodeCoverage*^ -filter:"+[xFunc.*]* -[xFunc.Tests*]* -[xFunc.*]*.Resource -[xFunc.*]*Exception"

    packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
deploy: off