version: '{branch}{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2019
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: YI6EFXDLg4sSRbxxqZdTI21IAWMt55JfDTTDpA6ljw7zq5UmXi9x5vbagzua5hqe
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore xFunc\xFunc.UI.sln
build:
  project: xFunc\xFunc.UI.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    "%userprofile%\.nuget\packages\opencover\4.7.922\tools\OpenCover.Console.exe" -register:user -output:coverage.xml -target:"dotnet.exe" -targetargs:"test xFunc.Tests\xFunc.Tests.csproj --no-build -c Release" -excludebyattribute:*.ExcludeFromCodeCoverage*^ -filter:"+[xFunc.*]* -[xFunc.Tests*]* -[xFunc.*]*.Resource -[xFunc.*]*Exception" -oldStyle

    "%userprofile%\.nuget\packages\coveralls.io\1.4.2\tools\coveralls.net.exe" --opencover coverage.xml
deploy: off